### ISSUE TITLE
wiserain/tvheadend:stable 버전 실행이 안됩니다

### ISSUE THREAD

**Issue by wowwoo** [wiserain/docker-tvheadend#25]
안녕하세요

7월 9일부터 안되었던 것 같습니다
실행이 안되어 웹 UI도 접속이 안되고
EPG 갱신도 되지 않아 이리 저리 확인해보니

wiserain/tvheadend:latest-4.3-2337

이 버전은 아무런 문제없이 작동이 됩니다

arm64 버전을 사용했습니다

감사합니다

**Comment by wiserain** [comment]
수정했습니다. 참고로 stable 태그는 더 이상 업데이트 되지 않습니다.
